### ISSUE TITLE
Is it possible to just add meteor's ecmascript package ? 

### ISSUE THREAD

**Issue by romans127** [vazco/universe-modules#20]
Is it possible to just add Meteor's ecmascript package. Just trying to learn the new ecmascript workflow, but would like to be on the bleeding edge from meteor.

**Comment by MacRusher** [comment]
What do you mean by "just add meteor's ecmascript package"?

If you're talking about adding it to the project of course you can do it.
`ecmascript` package should not change behavior of `universe:modules`, because it modifies only `*.js` files and our modules affect `*.import.js(x)`. But I haven't tested it yet.

Under the hood both packages uses the same `babel-compiler` package, except we add additional support for modules.

**Comment by romans127** [comment]
Very nice, 

Thank you for the fast reply. Yes I was just concerned that if I follow tutorials and use their ecmascript package if it would alter any expected behavior in modules. 

---

On that note. I really like this approach to development and will be working with it. I like the material-ui vs. ReactBootstrap approach, do you have instructions or documentation to convert this package [Material UI](https://atmospherejs.com/izzilab/material-ui) to use the modular approach with imports and exports ?

**Comment by MacRusher** [comment]
> do you have instructions or documentation to convert this package Material UI to use the modular approach with imports and exports ?

From my experience biggest problem with MUI in Meteor right now is browserify. You can get few instances of React and MUI theme manager goes nuts, so look out for that.

This package you mentioned exports `MUI` global variable anyway so you can use it directly or assign it in some file as an export to use it "modular way".
Not very clean but I don't have better idea right now, at least not without writing new MUI package for Meteor.
